spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/board;
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mariadb://board-db.cftsb4dcr8mq.ap-northeast-2.rds.amazonaws.com:3306/board
    username: admin
    password: zxc123456
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  error:
    whitelabel:
      enabled: false
    include-exception: true


file-dir: /home/ec2-user/file